"""
data_loader.py
==============
Responsible for loading the retail sales dataset from CSV files.

Supports:
    - Synthetic dataset generated by datasets/generate_dataset.py
    - Kaggle competition dataset (train.csv)
    - Auto-detection: prefers synthetic if Kaggle file not found

All loaded DataFrames are returned in a normalised, typed format ready
for the validation and feature-engineering pipeline.
"""

import sys
from pathlib import Path
from typing import Optional

import pandas as pd

_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT))

from config.settings import get_settings
from config.constants import DATE_FORMAT
from config.logging_config import get_logger

logger = get_logger(__name__)
settings = get_settings()


# ---------------------------------------------------------------------------
# Required and optional columns
# ---------------------------------------------------------------------------
_REQUIRED_COLS = {"date", "store", "item", "sales"}
_OPTIONAL_COLS = {
    "store_name", "item_name", "promotion", "holiday",
    "temperature", "rainfall", "festival", "weekend",
    "inventory", "price", "discount", "category", "supplier", "warehouse",
}

# Default values for optional columns when absent from the dataset
_DEFAULTS = {
    "store_name": "Unknown Store",
    "item_name":  "Unknown Item",
    "promotion":  0,
    "holiday":    0,
    "temperature": None,
    "rainfall":    None,
    "festival":   0,
    "weekend":    0,
    "inventory":  None,
    "price":      None,
    "discount":   0.0,
    "category":   "Unknown",
    "supplier":   "Unknown",
    "warehouse":  "Unknown",
}


def _detect_dataset_path() -> Path:
    """
    Auto-detect the best available dataset file in the datasets/ directory.

    Priority:
        1. synthetic_train.csv (generated locally)
        2. train.csv           (Kaggle competition file)

    Returns:
        Path to the best available CSV file.

    Raises:
        FileNotFoundError: if neither file exists.
    """
    synthetic = settings.datasets_dir / "synthetic_train.csv"
    kaggle    = settings.datasets_dir / "train.csv"

    if synthetic.exists():
        logger.info("Using synthetic dataset: %s", synthetic)
        return synthetic
    if kaggle.exists():
        logger.info("Using Kaggle dataset: %s", kaggle)
        return kaggle

    raise FileNotFoundError(
        f"No dataset found in {settings.datasets_dir}. "
        "Run `python datasets/generate_dataset.py` to create a synthetic dataset."
    )


def load_raw_dataset(path: Optional[Path] = None) -> pd.DataFrame:
    """
    Load raw sales data from CSV.

    Args:
        path: Optional explicit path to the CSV file.
              If None, auto-detection logic is used.

    Returns:
        Raw DataFrame with original column names preserved.

    Raises:
        FileNotFoundError: if the file cannot be found.
        ValueError:        if required columns are missing.
    """
    if path is None:
        path = _detect_dataset_path()

    logger.info("Loading dataset from: %s", path)
    df = pd.read_csv(path, low_memory=False)
    logger.info("Raw shape: %s", df.shape)

    # Normalise column names to lowercase + strip whitespace
    df.columns = df.columns.str.lower().str.strip()

    # Validate required columns
    missing = _REQUIRED_COLS - set(df.columns)
    if missing:
        raise ValueError(f"Dataset is missing required columns: {missing}")

    return df


def normalise_dataset(df: pd.DataFrame) -> pd.DataFrame:
    """
    Normalise a raw DataFrame to the canonical column set expected by the pipeline.

    Steps:
        1. Add missing optional columns with sensible defaults.
        2. Parse the date column to datetime.
        3. Cast numeric columns to correct dtypes.
        4. Derive weekend flag if not present.

    Args:
        df: Raw DataFrame from load_raw_dataset().

    Returns:
        Normalised DataFrame ready for validation.
    """
    df = df.copy()

    # ------------------------------------------------------------------
    # Fill missing optional columns
    # ------------------------------------------------------------------
    for col, default in _DEFAULTS.items():
        if col not in df.columns:
            df[col] = default
            logger.debug("Added missing column '%s' with default value.", col)

    # ------------------------------------------------------------------
    # Parse date column
    # ------------------------------------------------------------------
    df["date"] = pd.to_datetime(df["date"], format="mixed", dayfirst=False)

    # ------------------------------------------------------------------
    # Derive weekend flag from date if the column is all zeros / missing
    # ------------------------------------------------------------------
    if df["weekend"].sum() == 0:
        df["weekend"] = (df["date"].dt.weekday >= 5).astype(int)

    # ------------------------------------------------------------------
    # Type coercions
    # ------------------------------------------------------------------
    int_cols   = ["store", "item", "sales", "promotion", "holiday", "festival", "weekend"]
    float_cols = ["temperature", "rainfall", "price", "discount"]

    for col in int_cols:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0).astype(int)

    for col in float_cols:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    # Sort chronologically within each series
    df.sort_values(["store", "item", "date"], inplace=True)
    df.reset_index(drop=True, inplace=True)

    logger.info("Normalised dataset shape: %s", df.shape)
    return df


def load_series(store: int, item: int, df: Optional[pd.DataFrame] = None) -> pd.DataFrame:
    """
    Extract the univariate sales series for a specific Store × Item pair.

    Args:
        store: Store identifier (integer).
        item:  Item identifier (integer).
        df:    Pre-loaded DataFrame. If None, auto-loads and normalises.

    Returns:
        DataFrame filtered to the given Store × Item, sorted by date.

    Raises:
        ValueError: if the store/item combination has no data.
    """
    if df is None:
        raw = load_raw_dataset()
        df  = normalise_dataset(raw)

    mask   = (df["store"] == store) & (df["item"] == item)
    series = df.loc[mask].copy()

    if series.empty:
        raise ValueError(
            f"No data found for store={store}, item={item}. "
            "Verify that these IDs exist in the dataset."
        )

    series.sort_values("date", inplace=True)
    series.reset_index(drop=True, inplace=True)
    return series


def get_available_stores(df: Optional[pd.DataFrame] = None) -> list[int]:
    """
    Return the sorted list of unique store IDs in the dataset.

    Args:
        df: Pre-loaded DataFrame. If None, auto-loads.

    Returns:
        Sorted list of integer store codes.
    """
    if df is None:
        raw = load_raw_dataset()
        df  = normalise_dataset(raw)
    return sorted(df["store"].unique().tolist())


def get_available_items(df: Optional[pd.DataFrame] = None) -> list[int]:
    """
    Return the sorted list of unique item IDs in the dataset.

    Args:
        df: Pre-loaded DataFrame. If None, auto-loads.

    Returns:
        Sorted list of integer item codes.
    """
    if df is None:
        raw = load_raw_dataset()
        df  = normalise_dataset(raw)
    return sorted(df["item"].unique().tolist())
